import CP

/- 审计所有实际存在的公开定理，包含具体核心逆、奇偶连接及明确外部接口下的归一化。 -/
#check CP.Fractional.fractional_substitution
#check CP.Recurrence.three_term_recurrence
#check CP.Adjacent.adjacent_pair

#print axioms CP.R_mul_apply
#print axioms CP.mul_R_apply
#print axioms CP.R_sq
#print axioms CP.R_transpose
#print axioms CP.U_diag
#print axioms CP.U_below
#print axioms CP.T_above
#print axioms CP.coeff_one_sub_X_pow
#print axioms CP.signed_row_expansion
#print axioms CP.T_sq
#print axioms CP.choose_gram_sum
#print axioms CP.T_mul_transpose
#print axioms CP.K_sub_one
#print axioms CP.B_eq_signed_T_R
#print axioms CP.B_gram
#print axioms CP.det_U
#print axioms CP.det_G
#print axioms CP.bRow_coeff
#print axioms CP.bRow_expansion
#print axioms CP.B_mul_T
#print axioms CP.K_congruence
#print axioms CP.signDiagonal_sq
#print axioms CP.signDiagonal_transpose
#print axioms CP.G_signed_factor
#print axioms CP.G_inverse_factor
#print axioms CP.G_inverse_apply
#print axioms CP.blocks_mul
#print axioms CP.blocks_one
#print axioms CP.elimination_right_inverse
#print axioms CP.elimination_inverse
#print axioms CP.even_elimination_inverse
#print axioms CP.inverse_from_descent
#print axioms CP.inverse_from_descent_eq
#print axioms CP.det_ne_zero_from_right_inverse
#print axioms CP.det_update
#print axioms CP.selection_compress
#print axioms CP.det_diagonal_add_back
#print axioms CP.selection_intertwine
#print axioms CP.selected_congruence
#print axioms CP.front_upper_support
#print axioms CP.det_front_unit_upper
#print axioms CP.det_front_congruence
#print axioms CP.liftQ_transpose_alternating
#print axioms CP.liftQ_sandwich_apply
#print axioms CP.liftQ_G
#print axioms CP.liftQ_left_inverse
#print axioms CP.liftQ_injective
#print axioms CP.rank_liftQ
#print axioms CP.R_liftQ
#print axioms CP.liftQ_omega
#print axioms CP.delete_mul_of_zero_row
#print axioms CP.deleted_right_inverse
#print axioms CP.deleted_inverse
#print axioms CP.centerProjection_row
#print axioms CP.projected_center_row
#print axioms CP.mul_outer
#print axioms CP.centerProjection_mulVec
#print axioms CP.mul_centerProjection
#print axioms CP.outer_mul_projection_transpose
#print axioms CP.centerProjection_transpose
#print axioms CP.centered_product
#print axioms CP.centered_deleted_inverse
#print axioms CP.Adjacent.recurrence_eval
#print axioms CP.Adjacent.g_recurrence
#print axioms CP.Adjacent.W_step
#print axioms CP.Adjacent.W_initial
#print axioms CP.Adjacent.W_explicit
#print axioms CP.Adjacent.W_to_L
#print axioms CP.Adjacent.adjacent_pair
#print axioms CP.Fractional.chuSum_zero
#print axioms CP.Fractional.chuSum_step
#print axioms CP.Fractional.chuSum_edge
#print axioms CP.Fractional.finite_chu
#print axioms CP.Fractional.h_succ_coeff
#print axioms CP.Fractional.chu_product
#print axioms CP.Fractional.h_chu_sum
#print axioms CP.Fractional.h_coeff_recurrence
#print axioms CP.Fractional.subst_term_coeff
#print axioms CP.Fractional.substPoly_degree
#print axioms CP.Fractional.substPoly_coeff
#print axioms CP.Fractional.hyperOp_coeff
#print axioms CP.Fractional.h_hyperOp
#print axioms CP.Fractional.gauge_succ
#print axioms CP.Fractional.gap_hyperOp
#print axioms CP.Fractional.gap_coeff_recurrence
#print axioms CP.Fractional.subst_coeff_recurrence
#print axioms CP.Fractional.gap_subst_coeff_zero
#print axioms CP.Fractional.gap_subst_coeff
#print axioms CP.Fractional.gap_coeff_vanish
#print axioms CP.Fractional.reflect_h
#print axioms CP.Fractional.one_sub_X_pow_degree
#print axioms CP.Fractional.reflect_one_sub_X_pow
#print axioms CP.Fractional.gap_degree
#print axioms CP.Fractional.gap_reflect
#print axioms CP.Fractional.gap_decomposition
#print axioms CP.Fractional.gap_truncation
#print axioms CP.Fractional.h_comp_expansion
#print axioms CP.Fractional.subst_term_reflect
#print axioms CP.Fractional.subst_reflect
#print axioms CP.Fractional.fractional_cleared
#print axioms CP.Fractional.h_eval_expansion
#print axioms CP.Fractional.substPoly_eval
#print axioms CP.Fractional.fractional_substitution
#print axioms CP.Fractional.fractional_truncation
#print axioms CP.Fractional.substitution_denominator_constant
#print axioms CP.Recurrence.coeff_factorial
#print axioms CP.Recurrence.coeff_down_one
#print axioms CP.Recurrence.coeff_down_order
#print axioms CP.Recurrence.lowRange_bounds
#print axioms CP.Recurrence.denominator_factors
#print axioms CP.Recurrence.ratio_u1
#print axioms CP.Recurrence.coeff_down_order_general
#print axioms CP.Recurrence.ratio_v0
#print axioms CP.Recurrence.ratio_u2
#print axioms CP.Recurrence.ratio_v1
#print axioms CP.Recurrence.ratio_v2
#print axioms CP.Recurrence.ratio_v3
#print axioms CP.Recurrence.ratio_w2
#print axioms CP.Recurrence.beta_previous
#print axioms CP.Recurrence.ratio_certificate
#print axioms CP.Recurrence.low_coeff_recurrence
#print axioms CP.Recurrence.normalized_coeff
#print axioms CP.Recurrence.shifted_coeff
#print axioms CP.Recurrence.recLeft_coeff
#print axioms CP.Recurrence.recRight_coeff
#print axioms CP.Recurrence.normalized_degree
#print axioms CP.Recurrence.normalized_reflect
#print axioms CP.Recurrence.cubic_reflect
#print axioms CP.Recurrence.recLeft_reflect
#print axioms CP.Recurrence.recRight_reflect
#print axioms CP.Recurrence.recLeft_degree
#print axioms CP.Recurrence.recRight_degree
#print axioms CP.Recurrence.normalized_recurrence_large
#print axioms CP.Recurrence.normalized_recurrence_three
#print axioms CP.Recurrence.normalized_recurrence_four
#print axioms CP.Recurrence.normalized_recurrence
#print axioms CP.Recurrence.three_term_recurrence
#print axioms CP.h_zero
#print axioms CP.h_one
#print axioms CP.h_two
#print axioms CP.b_one
#print axioms CP.b_two
#print axioms CP.h_denominator_pos
#print axioms CP.h_coeff
#print axioms CP.b_formula
#print axioms CP.b_pos
#print axioms CP.h_natDegree_lt
#print axioms CP.h_coeff_palindrome
#print axioms CP.b_factorial
#print axioms CP.normalized_coeff_factorial
#print axioms CP.beta_succ_three
#print axioms CP.rho_ne_zero
#print axioms CP.rho_ne_one
#print axioms CP.rho_rho
#print axioms CP.rho_order_three
#print axioms CP.tau_rho
#print axioms CP.casoratian_step
#print axioms CP.plucker
#print axioms CP.recurrence_certificate

#print axioms CP.Kernel.polynomial_eq_of_eval_off
#print axioms CP.Kernel.reflect_eval
#print axioms CP.Kernel.h_reciprocal
#print axioms CP.Kernel.one_add_X_degree
#print axioms CP.Kernel.u_degree
#print axioms CP.Kernel.v_degree
#print axioms CP.Kernel.u_eval
#print axioms CP.Kernel.v_eval
#print axioms CP.Kernel.uStar_eval
#print axioms CP.Kernel.vStar_eval
#print axioms CP.Kernel.homogeneous_h_identity
#print axioms CP.Kernel.uStar_theta
#print axioms CP.Kernel.vStar_theta
#print axioms CP.Kernel.uvStar_pair
#print axioms CP.Kernel.reflect_twice
#print axioms CP.Kernel.reflect_degree
#print axioms CP.Kernel.sigmaPullback_eval
#print axioms CP.Kernel.uStar_theta_parity
#print axioms CP.Kernel.vStar_theta_parity
#print axioms CP.Kernel.sigma_u
#print axioms CP.Kernel.sigma_v
#print axioms CP.Kernel.sigma_uStar
#print axioms CP.Kernel.sigma_vStar
#print axioms CP.Kernel.sigma_u_eval
#print axioms CP.Kernel.sigma_v_eval
#print axioms CP.Kernel.sigma_uStar_eval
#print axioms CP.Kernel.sigma_vStar_eval
#print axioms CP.Kernel.one_add_X_ne_zero
#print axioms CP.Kernel.theta_pair
#print axioms CP.Kernel.theta_star_pair
#print axioms CP.Kernel.reflect_eval₂
#print axioms CP.Kernel.sigmaPullback_eval₂
#print axioms CP.Kernel.sigma_u_eval₂
#print axioms CP.Kernel.sigma_v_eval₂
#print axioms CP.Kernel.sigma_uStar_eval₂
#print axioms CP.Kernel.sigma_vStar_eval₂
#print axioms CP.Kernel.theta_comp_degree
#print axioms CP.Kernel.h_reciprocal_neg
#print axioms CP.Kernel.theta_u_reflect
#print axioms CP.Kernel.theta_v_reflect
#print axioms CP.Kernel.epsilon_sq
#print axioms CP.Kernel.theta_involution
#print axioms CP.Kernel.sigma_theta_u
#print axioms CP.Kernel.sigma_theta_v
#print axioms CP.Kernel.denominator_primitive
#print axioms CP.Kernel.primitive_dvd_of_fraction_dvd
#print axioms CP.Kernel.eval_inX
#print axioms CP.Kernel.eval_inY
#print axioms CP.Kernel.pNumerator_diagonal
#print axioms CP.Kernel.diagonal_factor_dvd
#print axioms CP.Kernel.coeffToField_eq_eval
#print axioms CP.Kernel.beval_inX
#print axioms CP.Kernel.beval_inY
#print axioms CP.Kernel.beval_xx
#print axioms CP.Kernel.beval_yy
#print axioms CP.Kernel.beval_constant
#print axioms CP.Kernel.field_one_add_ne_zero
#print axioms CP.Kernel.field_quadratic_ne_zero
#print axioms CP.Kernel.pNumerator_first_pair_root
#print axioms CP.Kernel.pNumerator_second_pair_root
#print axioms CP.Kernel.pNumerator_diagonal_field
#print axioms CP.Kernel.denominator_field_factor
#print axioms CP.Kernel.field_three_roots_distinct
#print axioms CP.Kernel.denominator_dvd_pNumerator
#print axioms CP.Kernel.denominator_mul_pKernel
#print axioms CP.Kernel.swap_inY
#print axioms CP.Kernel.swap_inX
#print axioms CP.Kernel.swap_xx
#print axioms CP.Kernel.swap_yy
#print axioms CP.Kernel.swap_constant
#print axioms CP.Kernel.swap_denominator
#print axioms CP.Kernel.denominator_degree
#print axioms CP.Kernel.inX_degree
#print axioms CP.Kernel.inY_degree
#print axioms CP.Kernel.bracket_degree
#print axioms CP.Kernel.bracket_sub_degree
#print axioms CP.Kernel.pair_factor_degrees
#print axioms CP.Kernel.fNumerator_degree
#print axioms CP.Kernel.swap_fNumerator_degree
#print axioms CP.Kernel.pNumerator_degree
#print axioms CP.Kernel.swap_pNumerator_degree
#print axioms CP.Kernel.pKernel_degree
#print axioms CP.Kernel.swap_pKernel_degree
#print axioms CP.Kernel.swap_coeff
#print axioms CP.Kernel.reflectXY_coeff
#print axioms CP.Kernel.swap_reflect_degree
#print axioms CP.Kernel.reflectXY_add
#print axioms CP.Kernel.reflectXY_sub
#print axioms CP.Kernel.reflectXY_scalar
#print axioms CP.Kernel.reflectXY_separated
#print axioms CP.Kernel.reflectXY_mul
#print axioms CP.Kernel.swap_coeff_degree
#print axioms CP.Kernel.reflect_firstBracket
#print axioms CP.Kernel.reflect_secondBracket
#print axioms CP.Kernel.bracket_degree_bounds
#print axioms CP.Kernel.fNumerator_reflect
#print axioms CP.Kernel.reflectXY_monomial
#print axioms CP.Kernel.reflectXY_one_one
#print axioms CP.Kernel.reflectXY_one_xx
#print axioms CP.Kernel.reflectXY_one_yy
#print axioms CP.Kernel.reflectXY_one_product
#print axioms CP.Kernel.reflectXY_pair_factors
#print axioms CP.Kernel.pair_factors_swap
#print axioms CP.Kernel.denominator_reflect
#print axioms CP.Kernel.tail_reflect
#print axioms CP.Kernel.pNumerator_reflect_difference
#print axioms CP.Kernel.pKernel_reflection
#print axioms CP.Kernel.antiDiagonalPolynomial_coeff
#print axioms CP.Kernel.pMatrix_reflection

#print axioms CP.Series.negPower_zero
#print axioms CP.Series.negPower_add
#print axioms CP.Series.negPower_eq_pow
#print axioms CP.Series.negPower_coeff
#print axioms CP.Series.positive_power_coeff
#print axioms CP.Series.negPower_cancel
#print axioms CP.Series.negPower_one_inverse
#print axioms CP.Series.transformed_expansion
#print axioms CP.Series.G_mulVec_coeff
#print axioms CP.Series.signed_vandermonde
#print axioms CP.Series.sum_fin_le
#print axioms CP.Series.conjugateCandidate_mul_G
#print axioms CP.Series.G_R_inverse
#print axioms CP.Series.G_R_inverse_apply
#print axioms CP.Series.rationalKernel_denominator
#print axioms CP.Series.negPower_coeff_C
#print axioms CP.Series.geometricColumn_coeff
#print axioms CP.Series.rescaled_geometric_coeff
#print axioms CP.Series.rationalKernel_coeff
#print axioms CP.Series.rationalKernel_coeff_degree
#print axioms CP.Series.even_G_R_inverse_kernel

#print axioms CP.Kernel.evalXY_inX
#print axioms CP.Kernel.evalXY_inY
#print axioms CP.Kernel.evalXY_xx
#print axioms CP.Kernel.evalXY_yy
#print axioms CP.Kernel.evalXY_constant
#print axioms CP.Kernel.evalXY_swap
#print axioms CP.Kernel.cNumerator_swap
#print axioms CP.Kernel.cNumerator_eval_swap
#print axioms CP.Kernel.cNumerator_diagonal
#print axioms CP.Kernel.cNumerator_first_root
#print axioms CP.Kernel.cNumerator_second_root
#print axioms CP.Kernel.beval_eq_evalXY
#print axioms CP.Kernel.denominator_dvd_of_roots
#print axioms CP.Kernel.denominator_dvd_cNumerator
#print axioms CP.Kernel.denominator_mul_cKernel
#print axioms CP.Kernel.cKernel_swap
#print axioms CP.Kernel.cNumerator_degree
#print axioms CP.Kernel.cKernel_degree
#print axioms CP.Kernel.swap_cKernel_degree
#print axioms CP.Kernel.cMatrix_skew
#print axioms CP.Kernel.reflect_alternant
#print axioms CP.Kernel.reflect_starAlternant
#print axioms CP.Kernel.alternant_degrees
#print axioms CP.Kernel.c_tail_reflect
#print axioms CP.Kernel.reflectXY_twice
#print axioms CP.Kernel.c_tail_reflect_second
#print axioms CP.Kernel.cNumerator_reflection
#print axioms CP.Kernel.cKernel_reflection
#print axioms CP.Kernel.cMatrix_reflection
#print axioms CP.Kernel.denominator_sigma
#print axioms CP.Kernel.cNumerator_sigma
#print axioms CP.Kernel.cKernel_sigma_cleared
#print axioms CP.Kernel.polynomialSeries_coeff
#print axioms CP.Kernel.polynomialSeries_evalXY
#print axioms CP.Kernel.substitutedSeries_evalXY
#print axioms CP.Kernel.substitutedSeries_expansion
#print axioms CP.Kernel.substitutedSeries_coeff
#print axioms CP.Kernel.G_cMatrix_series
#print axioms CP.Kernel.G_cMatrix_coeff
#print axioms CP.Kernel.remainder_coeff_zero
#print axioms CP.Kernel.hom_evalXY
#print axioms CP.Kernel.seriesToField_injective
#print axioms CP.Kernel.polynomialSeries_denominator_constant
#print axioms CP.Kernel.polynomialSeries_denominator_unit
#print axioms CP.Kernel.cKernel_series_cleared
#print axioms CP.Kernel.kernelSeries_denominator
#print axioms CP.Kernel.cKernel_series_exact
#print axioms CP.Kernel.cKernel_series_low_coeff
#print axioms CP.Kernel.jMatrix_reflection
#print axioms CP.Kernel.j_sub_c_reflection
#print axioms CP.Kernel.G_jMatrix
#print axioms CP.Kernel.cp_descent
#print axioms CP.Kernel.omega_mul_J_sub_C
#print axioms CP.Kernel.omega_inverse_eq_J_sub_C
#print axioms CP.Kernel.omega_det_ne_zero

#print axioms CP.Kernel.nu_ne_zero
#print axioms CP.Kernel.omega_kernel_vector
#print axioms CP.Kernel.omega_kernel_eq_span
#print axioms CP.Kernel.omega_kernel_finrank
#print axioms CP.Kernel.omega_odd_rank
#print axioms CP.Kernel.liftQ_polynomial
#print axioms CP.Kernel.liftQ_binomial
#print axioms CP.Kernel.G_inverse_gram_sum
#print axioms CP.Kernel.G_inverse_lift_update
#print axioms CP.Kernel.column_degree_lt
#print axioms CP.Kernel.swapXY_twice
#print axioms CP.Kernel.row_degree_lt
#print axioms CP.Kernel.lifted_column
#print axioms CP.Kernel.liftQ_column
#print axioms CP.Kernel.kernelMatrix_lift
#print axioms CP.Kernel.boundary_kernel_coeff
#print axioms CP.Kernel.oMatrix_lift
#print axioms CP.Kernel.sigmaPullback_series
#print axioms CP.Kernel.polynomialSeries_inX_coeff
#print axioms CP.Kernel.G_vector_series
#print axioms CP.Kernel.normalizedP_degree
#print axioms CP.Kernel.shifted_h_degree
#print axioms CP.Kernel.shiftedP_degree
#print axioms CP.Kernel.uStar_eq_shift_reflect
#print axioms CP.Kernel.nuPolynomial_factor
#print axioms CP.Kernel.nuPolynomial_degree
#print axioms CP.Kernel.nuPolynomial_reflect
#print axioms CP.Kernel.normalizedP_reflect
#print axioms CP.Kernel.nu_reversal
#print axioms CP.Kernel.normalizedP_eval_zero
#print axioms CP.Kernel.shiftedP_eval_neg_one
#print axioms CP.Kernel.nuPolynomial_eval_neg_one
#print axioms CP.Kernel.alternating_dot_nu
#print axioms CP.Kernel.alternating_dot_nu_ne_zero
#print axioms CP.Kernel.G_symmetric
#print axioms CP.Kernel.omega_skew
#print axioms CP.Kernel.jMatrix_skew
#print axioms CP.Kernel.gammaOdd_skew
#print axioms CP.Kernel.nu_left_omega_zero
#print axioms CP.Kernel.liftQ_transpose_kernel
#print axioms CP.Kernel.omega_gammaOdd
#print axioms CP.Kernel.gammaOdd_omega
#print axioms CP.Kernel.odd_deleted_inverse
#print axioms CP.Kernel.odd_deleted_mul_inverse
#print axioms CP.Kernel.normalizedP_fractional
#print axioms CP.Kernel.nu_sigma_polynomial
#print axioms CP.Kernel.nu_center_pos
#print axioms CP.Kernel.jMatrix_lift_update
#print axioms CP.Kernel.gammaOdd_eq_lift_inverse
#print axioms CP.Kernel.gammaOdd_alternating
#print axioms CP.Kernel.lift_omega_gammaOdd
#print axioms CP.Kernel.univariateSeries_apply
#print axioms CP.Kernel.univariateSeries_X
#print axioms CP.Kernel.univariateSeries_C
#print axioms CP.Kernel.nu_series_exact
#print axioms CP.Kernel.G_nu
#print axioms CP.Kernel.nuImage_degree
#print axioms CP.Kernel.nuImage_reflect
#print axioms CP.Kernel.nuImage_reversal
#print axioms CP.Kernel.omega_nu_zero

#print axioms CP.Connection.LL_one
#print axioms CP.Connection.LR_one
#print axioms CP.Connection.RL_one
#print axioms CP.Connection.RR_one
#print axioms CP.Connection.paired_inverse
#print axioms CP.Connection.gram_normalization
#print axioms CP.Connection.gram_normalization_blocks
#print axioms CP.Connection.inverseGram_RR
#print axioms CP.Connection.inverseGram_LR
#print axioms CP.Connection.inverseGram_RL
#print axioms CP.Connection.inverseGram_LL_congruence
#print axioms CP.Connection.freeD_inverseGram
#print axioms CP.Connection.freeD_congruence
#print axioms CP.Connection.even_connection
#print axioms CP.Connection.evenEliminated_right_inverse
#print axioms CP.Connection.evenEliminated_inverse
#print axioms CP.Connection.connectionB_det_ne_zero
#print axioms CP.Connection.even_baseL_det_ne_zero
#print axioms CP.Connection.even_candidate_inverse
#print axioms CP.Connection.even_candidate_tail_formula
#print axioms CP.Connection.B_entry
#print axioms CP.Connection.connectionB_LL
#print axioms CP.Connection.connectionB_LR
#print axioms CP.Connection.H0_entry
#print axioms CP.Connection.H0_below
#print axioms CP.Connection.H0_diagonal
#print axioms CP.Connection.det_H0
#print axioms CP.Connection.B_det_ne_zero
#print axioms CP.Connection.connectionB_blocks
#print axioms CP.Connection.paired_G_gram
#print axioms CP.Connection.paired_G_blocks
#print axioms CP.Connection.pairedEquiv_left
#print axioms CP.Connection.pairedEquiv_right
#print axioms CP.Connection.tailFirstEquiv_left_val
#print axioms CP.Connection.tailFirstEquiv_right_val
#print axioms CP.Connection.LL_blocks
#print axioms CP.Connection.LR_blocks
#print axioms CP.Connection.RL_blocks
#print axioms CP.Connection.RR_blocks
#print axioms CP.Connection.blocks_reconstruct
#print axioms CP.Connection.blocks_transpose
#print axioms CP.Connection.paired_mul
#print axioms CP.Connection.paired_add
#print axioms CP.Connection.paired_sub
#print axioms CP.Connection.paired_neg
#print axioms CP.Connection.paired_one
#print axioms CP.Connection.paired_even_right
#print axioms CP.Connection.paired_R_even
#print axioms CP.Connection.paired_anti_blocks
#print axioms CP.Connection.evenGamma_right_inverse
#print axioms CP.Connection.evenGamma_anti
#print axioms CP.Connection.paired_omega_blocks
#print axioms CP.Connection.evenX_right_inverse
#print axioms CP.Connection.evenX_inverse
#print axioms CP.Connection.evenX_det_ne_zero
#print axioms CP.Connection.trueD_eq_freeD_add_inverse
#print axioms CP.Connection.connection_congruence
#print axioms CP.Connection.head_diagonal_after_tailFirst
#print axioms CP.Connection.head_diagonal_congruence
#print axioms CP.Connection.baseL_congruence
#print axioms CP.Connection.blocks_add
#print axioms CP.Connection.blocks_sub
#print axioms CP.Connection.even_baseL_congruence
#print axioms CP.Connection.even_tailFirst_LL
#print axioms CP.Connection.trueD_apply
#print axioms CP.Connection.even_connection_native
#print axioms CP.Connection.gammaOdd_reflection
#print axioms CP.Connection.oMatrix_reflection
#print axioms CP.Connection.oMatrix_skew
#print axioms CP.Connection.oddCenter_rev
#print axioms CP.Connection.nu_rev_apply
#print axioms CP.Connection.oMatrix_center_zero
#print axioms CP.Connection.projected_entry
#print axioms CP.Connection.trueOddS_projected_fold
#print axioms CP.Connection.oddPair_left
#print axioms CP.Connection.oddPair_right
#print axioms CP.Connection.oddPair_center
#print axioms CP.Connection.odd_sum
#print axioms CP.Connection.oddLeft_ne_center
#print axioms CP.Connection.oddLeft_ne_rev
#print axioms CP.Connection.oddLeft_inj
#print axioms CP.Connection.centeredGammaOdd_reflect
#print axioms CP.Connection.centeredGammaOdd_center_row
#print axioms CP.Connection.odd_fold_right_inverse
#print axioms CP.Connection.odd_fold_inverse
#print axioms CP.Connection.oddX_det_ne_zero
#print axioms CP.Connection.trueOddS_eq_free_add_inverse
#print axioms CP.Connection.oddLower_left
#print axioms CP.Connection.oddLower_center
#print axioms CP.Connection.oddE_mul_apply
#print axioms CP.Connection.mul_oddE_castSucc
#print axioms CP.Connection.mul_oddE_last
#print axioms CP.Connection.omega_reflection_entry
#print axioms CP.Connection.oddZ_top
#print axioms CP.Connection.base_core_entry
#print axioms CP.Connection.odd_omega_coordinate
#print axioms CP.Connection.oddPair_rev
#print axioms CP.Connection.odd_baseL_congruence
#print axioms CP.Connection.oddEliminated_right_inverse
#print axioms CP.Connection.oddEliminated_inverse
#print axioms CP.Connection.oddZ_center_row
#print axioms CP.Connection.oddZ_mul_inverse
#print axioms CP.Connection.mul_oddE_transpose_apply
#print axioms CP.Connection.mul_oddCorrection_apply
#print axioms CP.Connection.inverseGram_odd_entry
#print axioms CP.Connection.freeOddS_entry
#print axioms CP.Connection.freeOddS_inverseGram
#print axioms CP.Connection.freeOddS_congruence
#print axioms CP.Connection.odd_baseL_det_ne_zero
#print axioms CP.Connection.odd_candidate_inverse
#print axioms CP.Connection.odd_candidate_tail_formula
#print axioms CP.Connection.odd_connection
#print axioms CP.Connection.odd_connection_native
#print axioms CP.Connection.candidate_add_back
#print axioms CP.Connection.reversed_front_det
#print axioms CP.Connection.candidate_tail_det
#print axioms CP.Connection.even_finite_bridge
#print axioms CP.Connection.odd_finite_bridge
#print axioms CP.Connection.trueE_LL
#print axioms CP.Connection.trueE_Lc
#print axioms CP.Connection.trueE_cL
#print axioms CP.Connection.trueE_cc
#print axioms CP.Connection.borderTail_left
#print axioms CP.Connection.borderTail_last
#print axioms CP.Connection.trueE_tail_blocks
#print axioms CP.Connection.det_oddAlpha
#print axioms CP.Connection.oddAlpha_inverse
#print axioms CP.Connection.trueE_tail_det
#print axioms CP.Connection.tailDiagonal_zero
#print axioms CP.Connection.kernelTail_zero
#print axioms CP.Connection.borderTail_zero
#print axioms CP.Connection.even_scalar_relation
#print axioms CP.Connection.odd_scalar_relation
#print axioms CP.Connection.trueE_det
#print axioms CP.Connection.even_relative_bridge
#print axioms CP.Connection.odd_relative_bridge
#print axioms CP.Connection.odd_bordered_finite_bridge
#print axioms CP.Connection.asmProduct_pos
#print axioms CP.Connection.even_scalar_normalized
#print axioms CP.Connection.odd_scalar_normalized
#print axioms CP.Connection.even_bridge_normalized
#print axioms CP.Connection.odd_bridge_normalized
#print axioms CP.StageOne.even_finite_bridge
#print axioms CP.StageOne.odd_finite_bridge
#print axioms CP.StageOne.even_normalized
#print axioms CP.StageOne.odd_normalized

#check CP.Kernel.omega_mul_J_sub_C
#check CP.Kernel.omega_inverse_eq_J_sub_C
#check CP.StageOne.even_finite_bridge
#check CP.StageOne.odd_finite_bridge
#check CP.StageOne.even_normalized
#check CP.StageOne.odd_normalized
#print CP.Connection.EvenNormalizationInput
#print CP.Connection.OddNormalizationInput
