import CP.Polynomial
import CP.BinomialMatrices
import CP.BinomialMatrices.Truncation
import CP.BinomialMatrices.KernelTruncation
import CP.Polynomial.Fractional
import CP.Polynomial.Recurrence
import CP.Polynomial.Adjacent
import CP.Kernel.Univariate
import CP.Kernel.Transport
import CP.Kernel.Theta
import CP.Kernel.Bivariate
import CP.Kernel.Roots
import CP.Kernel.Bidegree
import CP.Kernel.Reflection
import CP.Kernel.ReflectionIdentity
import CP.Kernel.ActualC
import CP.Kernel.CReflection
import CP.Kernel.DescentAlgebra
import CP.Kernel.SeriesCoefficients
import CP.Kernel.ExactTruncation
import CP.Kernel.EvenInverse
import CP.EvenBridge
import CP.OddBridge
import CP.Kernel.Odd.Lift
import CP.Kernel.Odd.KernelLift
import CP.Kernel.Odd.Upgrade
import CP.Kernel.Odd.NullPolynomial
import CP.Kernel.Odd.NullSubstitution
import CP.Kernel.Odd.SigmaSeries
import CP.Kernel.Odd.NullVector
import CP.Kernel.Odd.Projection
import CP.Kernel.Odd.Nullspace
import CP.BlockElimination
import CP.FiniteBridge
import CP.Connection.Coordinates
import CP.Connection.BinomialBlocks
import CP.Connection.EvenFold
import CP.Connection.CandidateCongruence
import CP.Connection.EvenElimination
import CP.Connection.EvenGram
import CP.Connection.EvenNative
import CP.Connection.OddFold
import CP.Connection.OddInverseFold
import CP.Connection.OddCandidate
import CP.Connection.OddNormalization
import CP.Connection.OddGram
import CP.Connection.OddConnection
import CP.Normalization.DiagonalBridge
import CP.Normalization.OddBorder
import CP.Normalization.Scalar
import CP.StageOne
